name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          config_file: docs/Doxyfile.in
          github_pages_repo: blgnksy/blgnksy.github.io
          github_pages_branch: naster  # or 'master' - use whatever branch your blog uses
          target_folder: extremeC  # or 'docs/project-name'