name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout current repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install Doxygen
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # Generate documentation
      - name: Generate Documentation
        run: |
          cd docs
          doxygen Doxyfile.in

      # Deploy to GitHub Pages in another repository
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          repository-name: blgnksy/blgnksy.github.io
          branch: master  # The branch your blog uses
          folder: docs/html  # The folder containing Doxygen output
          target-folder: extremeC  # Where to place it in the target repo
          clean: true  # Remove old files in target folder
          clean-exclude: |
            !extremeC/**