name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout current repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install Doxygen
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # Generate documentation
      - name: Generate Documentation
        run: |
          cd docs
          doxygen Doxyfile.in
          # Add .nojekyll to prevent Jekyll processing
          touch html/.nojekyll
          # Debug: Check what files were generated
          echo "Files in docs/html:"
          ls -la html/

      # Deploy to gh-pages branch of current repo
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use built-in token
          branch: gh-pages  # Deploy to gh-pages branch
          folder: docs/html
          clean: true